# Generated by Django 4.0.4 on 2022-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Try',
                'verbose_name_plural': 'Tries',
            },
        ),
    ]
