# Generated by Django 4.0.6 on 2022-07-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone Number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('profile', models.ImageField(default='profiles/unknown_user.png', null=True, upload_to='profiles/%Y/', verbose_name='Picture')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=60)),
                ('document_content', models.TextField()),
                ('document', models.FileField(upload_to='documents/%Y/', verbose_name='Document')),
                ('plagiarism_status', models.BooleanField(default=False, null=True)),
                ('plagiarism_score', models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True)),
                ('j_coefficient', models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True)),
                ('containment_measure', models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True)),
                ('common_words', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('difficult_words', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('wrong_words', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
