# Generated by Django 4.0.5 on 2022-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theusers',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='theusers',
            name='profile',
            field=models.ImageField(default='profiles/unknown_user.png', null=True, upload_to='profiles/%Y/', verbose_name='Picture'),
        ),
    ]
