# Generated by Django 4.0.4 on 2022-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_created=True, verbose_name='Added Date')),
                ('document_title', models.CharField(max_length=75, verbose_name='Documet Title')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('document_content', models.CharField(max_length=12000000000000, verbose_name='Document Content')),
            ],
        ),
    ]
