# Generated by Django 4.0.5 on 2022-06-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theusers',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
